In [3]:
import numpy as np

In [14]:
log_R       =  np.ones((3, 3))
log_R
a= np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a[1, :2]

array([4, 5])

In [31]:
from scipy.stats import norm
from   scipy.special import logsumexp

In [28]:
x=norm([1,2,3], [1,1,1])
x

In [47]:
x=norm.pdf(2,[1,2,3,4,5],[1,1,1,1,1])
x

array([0.24197072, 0.39894228, 0.24197072, 0.05399097, 0.00443185])

In [5]:
a= np.zeros(4)
a

array([0., 0., 0., 0.])

In [6]:
a = np.array([1,2,3,4,5,6,7,8,10])
a[:-1]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
invW = np.tile(np.identity()[np.newaxis], (self.n_class, 1, 1)) 

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]])

In [41]:
dim=4
n_class=6

invW = np.tile(np.identity(2)[np.newaxis], (3, 1, 1)) 
invW

array([[[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]]])

In [24]:
a=np.identity(2)
a

array([[1., 0.],
       [0., 1.]])

In [25]:
a=np.array([[1,2,3]])
a
from scipy.stats import multivariate_normal

In [37]:
mean = np.array([1,1])
cov = np.array([[1,0],[0,1]])
x=[1,1]
multivariate_normal(mean=mean, cov=cov).logpdf(x)
mean_params = np.array([3,4])
t = np.vstack((mean,mean_params))
t = np.vstack(([0,0],t))
t
t[:3]

array([[0, 0],
       [1, 1],
       [3, 4]])

In [76]:
mean = np.array([[1,2],[3,4],[5,6]])
invW = np.tile(np.identity(2)[np.newaxis], (3, 1, 1)) 
x = np.array([1,2])
p_val = []
for i in range(len(mean)):
    p_val.append(multivariate_normal(mean[i],invW[i]).logpdf(x))
p_val

[-1.8378770664093453, -5.837877066409345, -17.837877066409344]

In [61]:
mean[:2]
from   scipy.stats import norm

In [71]:
x=3
norm([1,2,3,4], [1,1,1,1]).logpdf(x)

array([-2.91893853, -1.41893853, -0.91893853, -1.41893853])

In [93]:
a = np.array([[1,2]])
b = np.array([3,4])
c = np.vstack((a,b))

c

array([[1, 2],
       [3, 4]])

In [97]:
a_m = np.array([[1,2],[3,4],[5,6]])
x = np.array([1,2])
fix_var = np.identity(2)
a_var = np.tile(np.identity(2)[np.newaxis], (4, 1, 1))
initial = np.array([0,0])
import numpy.linalg as LA
# inner = np.dot(a_var[:-1],a_m)+np.dot(fix_var,x)
# answer = np.dot(np.linalg.inv(a_var),inner)
for i in range(len(a_m)):
    inner = np.dot(a_var[i],a_m[i])+np.dot(fix_var,x)
    print(f'a_mi:{a_m[i]}')
    print(f'a_var[i+1]:{a_var[i+1]}')
    answer = np.dot(np.linalg.inv(a_var[i+1]),inner)
    initial = np.vstack((initial,answer))
initial


a_mi:[1 2]
a_var[i+1]:[[1. 0.]
 [0. 1.]]
a_mi:[3 4]
a_var[i+1]:[[1. 0.]
 [0. 1.]]
a_mi:[5 6]
a_var[i+1]:[[1. 0.]
 [0. 1.]]


array([[0., 0.],
       [2., 4.],
       [4., 6.],
       [6., 8.]])

In [84]:
invW = np.tile(np.identity(2)[np.newaxis], (3, 1, 1)) 
sigma  = np.identity(2)
invW + sigma

array([[[2., 0.],
        [0., 2.]],

       [[2., 0.],
        [0., 2.]],

       [[2., 0.],
        [0., 2.]]])

TypeError: 'int' object is not iterable

In [94]:
np.sqrt(np.identity(2))

array([[1., 0.],
       [0., 1.]])

In [98]:
x=np.array([[1,2],[3,4]])
y = np.array([[1,2]])
x+y

array([[2, 4],
       [4, 6]])