In [1]:
import numpy as np

In [14]:
log_R       =  np.ones((3, 3))
log_R
a= np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a[1, :2]

array([4, 5])

In [31]:
from scipy.stats import norm
from   scipy.special import logsumexp

In [28]:
x=norm([1,2,3], [1,1,1])
x

In [47]:
x=norm.pdf(2,[1,2,3,4,5],[1,1,1,1,1])
x

array([0.24197072, 0.39894228, 0.24197072, 0.05399097, 0.00443185])